### ISSUE TITLE
no pdf device in Printer Setup :-(

### ISSUE THREAD

**Issue by fortranboomer** [mlund/xmgr-resurrection#3]
First, many (really many) thanks for your resurrecting xmgr. I first used xmgr way back when it was xvgr on a Sun workstation (~1991).

I recall last time I used xmgr there was an additional device in the printer setup to file print to pdf. So, this is not really an issue, it is more of a heads-up in case you fiddle with this resurrected xmgr: could that pdf device return, at least for macOS using some sort of macports pdf lib ?

Cheers,
Peter

**Comment by mlund** [comment]
Hi Peter, thanks for the encouragement; I know many people still prefer this solid program and it's amazing the gui still compiles with fairly modest changes. Regarding PDF, I don't see any options for this in the original source tree, i.e. the word "PDF" doesn't appear anywhere. I know a pdf option exists in _xmgrace_ which is the next iteration of xmgr.

**Comment by I-Thompson** [comment]
I attach my preferred way of making pdf files, even fror xmgrace.
The attached python code produces a tight bounding box, and files suitable of publication without further problem.
(remove .txt extension, etc).

[epsproc.py.txt](https://github.com/mlund/xmgr-resurrection/files/6219174/epsproc.py.txt)
