### ISSUE TITLE
Compilation in Big Sur

### ISSUE THREAD

**Issue by I-Thompson** [mlund/xmgr-resurrection#4]
I too much prefer this API over that of xmgrace.

But on my new mac, here seems to be some issue with clang 12.0:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -v
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0

At the very start in cephes, this gives:

> make
[  0%] Building C object cephes/CMakeFiles/cephes.dir/airy.c.o
In file included from /Users/ian/Dove/grace/xmgr/cephes/airy.c:59:
In file included from /Users/ian/Dove/grace/xmgr/cephes/mconf.h:70:
/Users/ian/Dove/grace/xmgr/cmath.h:108:12: error: expected identifier or '('
extern int isfinite ( double x );
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/math.h:155:7: note: expanded from macro
      'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
      ^
In file included from /Users/ian/Dove/grace/xmgr/cephes/airy.c:59:
In file included from /Users/ian/Dove/grace/xmgr/cephes/mconf.h:70:
/Users/ian/Dove/grace/xmgr/cmath.h:108:12: error: expected ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/math.h:155:7: note: expanded from macro
      'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
      ^
/Users/ian/Dove/grace/xmgr/cmath.h:108:12: note: to match this '('
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/math.h:155:5: note: expanded from macro
      'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
    ^
2 errors generated.
make[2]: *** [cephes/CMakeFiles/cephes.dir/airy.c.o] Error 1
make[1]: *** [cephes/CMakeFiles/cephes.dir/all] Error 2
make: *** [all] Error 2

It may be, according to  
https://superuser.com/questions/1555092/cmath-compilation-errors-with-clang-10-on-mac-os-catalina  
that we are not accessing /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h (which does have isinfinite!)

In which case, my title with Big Sur is not accurate.  Sorry.

**Comment by mlund** [comment]
I actually had this problem some months ago when I first got the M1, but forgot. Could you please try the attached patch with `git apply`? Will likely need to polish a little bit before pushing to the repository.

~~~ diff
diff --git a/cephes/isfinite.c b/cephes/isfinite.c
index e4b97f8..9ceff3e 100644
--- a/cephes/isfinite.c
+++ b/cephes/isfinite.c
@@ -17,6 +17,8 @@ Cephes Math Library Release 2.3:  March, 1995
 Copyright 1984, 1995 by Stephen L. Moshier
 */
 
+#define HAVE_ISFINITE
+
 
 #include "mconf.h"
 
diff --git a/cmath.h b/cmath.h
index 3e7c100..8aa2359 100644
--- a/cmath.h
+++ b/cmath.h
@@ -105,7 +105,7 @@ extern double jn ( int n, double x );
 #ifndef HAVE_FINITE
 #  define finite isfinite
 #  ifndef HAVE_ISFINITE
-extern int isfinite ( double x );
+//extern int isfinite ( double x );
 #  endif
 #endif
~~~

**Comment by I-Thompson** [comment]
Thanks!  the xmgr and grconvert compiled perfectly.

Only minor issue is that /usr/local/xmgr/bin is not in my path to start with.
