### ISSUE TITLE
Compiling on Ubuntu 22.04

### ISSUE THREAD

**Issue by vrossum** [mlund/xmgr-resurrection#5]
Hi

On Ubuntu 22.04 I get the error.

/usr/local/src/xmgr-resurrection-master/src/files.c:2591:14: fatal error: rpc/rpc.h: No such file or directory

apt-file find rpc/rpc.h returns
libntirpc-dev: /usr/include/ntirpc/rpc/rpc.h
But after installing libntirpc-dev, the compilation error remains.

I guess /usr/include/ntirpc needs to be included at build.

**Comment by mlund** [comment]
Thanks for the bug report - just should now be fixed. Please checkout the newest commit and see if this works for you?

**Comment by vrossum** [comment]
Yes, that works. Thanks!
